language: node_js
os: linux
dist: bionic

node_js: 
  - node

script:
  - npm run lint
  - npm run test

notifications:
recipients:
  - blasteralex@yandex.ru
email:
  on_success: change
  on_failure: change